services:
  endee:
    image: endeeio/endee-server:latest
    container_name: endee-server
    ports:
      - "8080:8080"
    environment:
      NDD_AUTH_TOKEN: ""
    volumes:
      - endee-data:/data
    restart: unless-stopped

  recommender:
    build: .
    container_name: recommender-app
    ports:
      - "8501:8501"
    environment:
      - ENDEE_URL=http://endee:8080
    depends_on:
      - endee
    restart: unless-stopped

volumes:
  endee-data: